version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
  web:
    build: .
    volumes:
      - .:/code
    command: bash -c 'python manage.py collectstatic --noinput
              && python manage.py makemigrations
              && python manage.py migrate
              && python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    volumes:
      - .:/code
    command: 'celery -A test_dir worker -l debug'
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    volumes:
      - .:/code
    command: 'celery -A test_dir beat -l debug'
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
